// Shared types for the data-sync engine.

/** Collections included in a content export/import (excludes Users, ContactMessages). */
export const CONTENT_COLLECTIONS = [
  'document-categories',
  'documents',
  'tags',
  'authors',
  'articles',
  'technologies',
  'projects',
  'social-profiles',
] as const
export type ContentCollection = (typeof CONTENT_COLLECTIONS)[number]

/** Globals included in a content export/import. */
export const SYNC_GLOBALS = ['site-config', 'home', 'nav'] as const
export type SyncGlobal = (typeof SYNC_GLOBALS)[number]

/** Archive manifest schema version — bump when the on-disk format changes. */
export const SCHEMA_VERSION = 1 as const

export interface ArchiveManifest {
  schemaVersion: typeof SCHEMA_VERSION
  tool: 'portfolio-data-sync'
  exportedAt: string
  sourceEnv: string
  payloadVersion: string
  counts: Record<string, number>
}

/** A relationship field on a doc that must be rewritten id ↔ natural-key. */
export interface RelationDef {
  field: string
  to: ContentCollection
  hasMany: boolean
  required?: boolean
  /** Self-referential (e.g. articles.relatedArticles) — resolve in a 2nd pass on import. */
  selfRef?: boolean
}

export interface ImportErrorEntry {
  collection: string
  key: string
  message: string
}

export interface ImportReport {
  created: Record<string, number>
  updated: Record<string, number>
  unchanged: Record<string, number>
  errors: ImportErrorEntry[]
  /** Path of the pre-import DB backup, when a real import ran. */
  backupPath?: string
  dryRun: boolean
}

/** Fields Payload manages automatically — never export them. */
export const INTERNAL_FIELDS = ['id', 'createdAt', 'updatedAt'] as const

/** Upload auto-fields — regenerated by Payload on re-upload, so never export them. */
export const UPLOAD_AUTO_FIELDS = [
  'url',
  'thumbnailURL',
  'mimeType',
  'filesize',
  'width',
  'height',
  'focalX',
  'focalY',
] as const
